# Generated by Django 5.1.6 on 2025-02-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('ContactId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(max_length=100)),
                ('Phone', models.IntegerField(null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Address', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackModel',
            fields=[
                ('FeedBackId', models.BigAutoField(primary_key=True, serialize=False)),
                ('FName', models.TextField(max_length=100, null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Message', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
