# Generated by Django 5.1.6 on 2025-03-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('DistrictId', models.BigAutoField(primary_key=True, serialize=False)),
                ('District', models.TextField(max_length=40, null=True, unique=True)),
            ],
        ),
    ]
