# Generated by Django 5.1.6 on 2025-03-03 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_districtmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('LocationId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Location', models.TextField(max_length=40, null=True)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.districtmodel')),
            ],
        ),
    ]
