# Generated by Django 5.1.6 on 2025-03-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_locationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('CategoryId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Category', models.TextField(max_length=50, unique=True)),
            ],
        ),
    ]
