# Generated by Django 5.1.6 on 2025-03-03 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_CategoryModel',
            fields=[
                ('Sub_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Sub_Category', models.TextField(max_length=50, unique=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.categorymodel')),
            ],
        ),
    ]
