# Generated by Django 5.1.6 on 2025-03-04 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_sub_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('LoginId', models.BigAutoField(primary_key=True, serialize=False)),
                ('UserName', models.TextField(max_length=100, null=True)),
                ('Password', models.TextField(max_length=100, null=True)),
                ('Role', models.TextField(max_length=100, null=True)),
                ('Status', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='feedbackmodel',
            old_name='Email',
            new_name='Bookname',
        ),
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='Phone',
        ),
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('RegisterId', models.BigAutoField(primary_key=True, serialize=False)),
                ('RegisterName', models.TextField(max_length=100, null=True)),
                ('RegisterAddress', models.TextField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=10, null=True)),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.districtmodel')),
                ('Location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.locationmodel')),
                ('LoginId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.loginmodel')),
            ],
        ),
    ]
