# Generated by Django 5.1.6 on 2025-03-07 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_loginmodel_rename_email_feedbackmodel_bookname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='FeedBackdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
