# Generated by Django 5.1.6 on 2025-03-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_feedbackmodel_feedbackdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackmodel',
            options={'ordering': ['-FeedBackdate']},
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='Bookname',
            field=models.TextField(null=True),
        ),
    ]
