# Generated by Django 5.1.6 on 2025-03-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_alter_feedbackmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='Bookimg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
