# Generated by Django 5.1.7 on 2025-03-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_categorymodel_bookimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='Bookname',
        ),
    ]
