# Generated by Django 5.1.6 on 2025-03-31 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_remove_feedbackmodel_bookname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBackModel',
        ),
    ]
