# Generated by Django 5.1.6 on 2025-03-12 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberofBooksModel',
            fields=[
                ('Numid', models.AutoField(primary_key=True, serialize=False)),
                ('numberofbooks', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bookregistrationmodel',
            name='numberofbooks',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthorApp.numberofbooksmodel'),
        ),
    ]
