# Generated by Django 5.1.6 on 2025-03-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorApp', '0002_numberofbooksmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberofbooksmodel',
            name='Bid',
            field=models.ManyToManyField(to='AuthorApp.bookregistrationmodel', verbose_name='Books'),
        ),
    ]
