# Generated by Django 5.1.6 on 2025-03-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorApp', '0003_numberofbooksmodel_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookregistrationmodel',
            name='numberofbooks',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.DeleteModel(
            name='NumberofBooksModel',
        ),
    ]
