# Generated by Django 5.1.6 on 2025-03-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorApp', '0004_alter_bookregistrationmodel_numberofbooks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookregistrationmodel',
            name='BookRegidate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
