# Generated by Django 5.1.6 on 2025-03-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorApp', '0005_bookregistrationmodel_bookregidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookregistrationmodel',
            name='total_sales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
