# Generated by Django 5.1.6 on 2025-03-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorApp', '0006_bookregistrationmodel_total_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookregistrationmodel',
            name='BookRegidate',
            field=models.DateField(null=True),
        ),
    ]
