# Generated by Django 5.1.6 on 2025-04-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorApp', '0008_alter_bookregistrationmodel_bookregidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookregistrationmodel',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
