# Generated by Django 5.1.6 on 2025-03-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0009_categorymodel_bookimg'),
        ('AuthorApp', '0008_alter_bookregistrationmodel_bookregidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModels',
            fields=[
                ('PaymentId', models.AutoField(primary_key=True, serialize=False)),
                ('CardNo', models.BigIntegerField()),
                ('CardName', models.CharField(max_length=40)),
                ('CVV', models.IntegerField()),
                ('Deliveryaddress', models.TextField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookingModels',
            fields=[
                ('BookingId', models.AutoField(primary_key=True, serialize=False)),
                ('Bookingdate', models.DateField(auto_now_add=True)),
                ('Totalamount', models.FloatField(default=True)),
                ('Billnumber', models.IntegerField(default=100)),
                ('status', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthorApp.bookregistrationmodel')),
                ('custerid', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.loginmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CartItemModel',
            fields=[
                ('CartId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.BigIntegerField(default=1)),
                ('status', models.CharField(max_length=30)),
                ('Bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthorApp.bookregistrationmodel')),
                ('custerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.loginmodel')),
            ],
        ),
        migrations.CreateModel(
            name='secondhandBookModel',
            fields=[
                ('Secondid', models.AutoField(primary_key=True, serialize=False)),
                ('BookName', models.TextField(max_length=100, null=True, unique=True)),
                ('noofpages', models.IntegerField(null=True)),
                ('MRP', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('year', models.DateField(blank=True, default=None, null=True)),
                ('language', models.TextField(max_length=20, null=True)),
                ('Author', models.TextField(max_length=20, null=True)),
                ('Publisher', models.TextField(max_length=20, null=True)),
                ('Edition', models.TextField(max_length=20, null=True)),
                ('Bookimg', models.ImageField(null=True, upload_to='')),
                ('username', models.TextField(null=True)),
                ('Status', models.TextField(max_length=100, null=True)),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.categorymodel')),
            ],
        ),
    ]
