# Generated by Django 5.1.7 on 2025-03-28 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_categorymodel_bookimg'),
        ('AuthorApp', '0008_alter_bookregistrationmodel_bookregidate'),
        ('bookstore', '0002_remove_bookingmodels_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Booking_master',
            fields=[
                ('masterid', models.AutoField(primary_key=True, serialize=False)),
                ('Bookingdate', models.DateField(auto_now_add=True)),
                ('Total', models.FloatField(default=0.0)),
                ('Billnumber', models.IntegerField(default=100)),
                ('status', models.CharField(max_length=100)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthorApp.bookregistrationmodel')),
                ('customerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.loginmodel')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Booking',
            fields=[
                ('BookingId', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthorApp.bookregistrationmodel')),
                ('customerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.loginmodel')),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.tbl_booking_master')),
            ],
        ),
        migrations.DeleteModel(
            name='BookingModels',
        ),
    ]
