# Generated by Django 5.1.7 on 2025-03-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_tbl_booking_master_tbl_booking_delete_bookingmodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='customerid',
        ),
        migrations.RemoveField(
            model_name='tbl_booking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tbl_booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tbl_booking_master',
            name='books',
        ),
    ]
