# Generated by Django 5.1.7 on 2025-03-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_remove_tbl_booking_customerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='status',
            field=models.CharField(default='not booking', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_booking_master',
            name='status',
            field=models.CharField(default='not booking', max_length=100, null=True),
        ),
    ]
