# Generated by Django 5.1.7 on 2025-03-28 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_remove_feedbackmodel_bookname'),
        ('bookstore', '0005_tbl_booking_status_alter_tbl_booking_master_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='customerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.loginmodel'),
        ),
    ]
