# Generated by Django 5.1.6 on 2025-03-31 23:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_tbl_booking_customerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackModel',
            fields=[
                ('FeedBackId', models.BigAutoField(primary_key=True, serialize=False)),
                ('FName', models.TextField(max_length=100, null=True)),
                ('Message', models.TextField(max_length=200, null=True)),
                ('FeedBackdate', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.tbl_booking')),
            ],
            options={
                'ordering': ['-FeedBackdate'],
            },
        ),
    ]
