# Generated by Django 5.1.6 on 2025-03-31 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_feedbackmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='user',
        ),
    ]
