# Generated by Django 5.1.6 on 2025-04-01 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_delete_feedbackmodel'),
        ('bookstore', '0010_buynow'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyNowModel',
            fields=[
                ('buynowid', models.AutoField(primary_key=True, serialize=False)),
                ('bookname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.secondhandbookmodel')),
                ('custerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.loginmodel')),
            ],
        ),
    ]
