# Generated by Django 5.1.6 on 2025-04-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_buynowmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buynow',
        ),
    ]
