# Generated by Django 5.1.6 on 2025-04-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_delete_buynow'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='rating',
            field=models.IntegerField(default=0, max_length=10, null=True),
        ),
    ]
